// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvKa91YKu0pPGShAcNsH-prmBPWzfHd4',
    appId: '1:603982472173:web:d9f00eda1a4b2de795bde4',
    messagingSenderId: '603982472173',
    projectId: 'casino-app-c9433',
    authDomain: 'casino-app-c9433.firebaseapp.com',
    storageBucket: 'casino-app-c9433.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNu-62VkRuGTqeKE45rqrSxYDz6Y6M5w',
    appId: '1:603982472173:android:b0b0989e6ca3c23495bde4',
    messagingSenderId: '603982472173',
    projectId: 'casino-app-c9433',
    storageBucket: 'casino-app-c9433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnyVhoXvrast5WFDFKJEi5BwtUVYTSqy8',
    appId: '1:603982472173:ios:fa5472e5271a812295bde4',
    messagingSenderId: '603982472173',
    projectId: 'casino-app-c9433',
    storageBucket: 'casino-app-c9433.appspot.com',
    iosClientId: '603982472173-oob8pt8ca552rvkgvdbkq8fhio57ksll.apps.googleusercontent.com',
    iosBundleId: 'com.example.casinoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnyVhoXvrast5WFDFKJEi5BwtUVYTSqy8',
    appId: '1:603982472173:ios:fa5472e5271a812295bde4',
    messagingSenderId: '603982472173',
    projectId: 'casino-app-c9433',
    storageBucket: 'casino-app-c9433.appspot.com',
    iosClientId: '603982472173-oob8pt8ca552rvkgvdbkq8fhio57ksll.apps.googleusercontent.com',
    iosBundleId: 'com.example.casinoApp',
  );
}
